# Generated by Django 4.2.17 on 2025-05-29 15:29

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "operation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(999999999),
                        ]
                    ),
                ),
                (
                    "payer_inn",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{10}$", message="Длина должна быть ровно 10 цифр"
                            )
                        ],
                    ),
                ),
                ("document_number", models.CharField(max_length=50)),
                ("document_date", models.DateTimeField()),
            ],
        ),
    ]
