# Generated by Django 4.2.17 on 2025-05-29 17:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BalanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Изменение баланса",
                    ),
                ),
                (
                    "previous_balance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Баланс до изменения",
                    ),
                ),
                (
                    "new_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Новый баланс"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Лог баланса",
                "verbose_name_plural": "Логи баланса",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inn",
                    models.CharField(max_length=12, unique=True, verbose_name="ИНН"),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Баланс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opearion_id",
                    models.UUIDField(unique=True, verbose_name="UUID операции"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Сумма платежа",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(max_length=50, verbose_name="Номер документа"),
                ),
                ("document_date", models.DateTimeField(verbose_name="Дата документа")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="api.organization",
                        verbose_name="Организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
            },
        ),
        migrations.DeleteModel(
            name="Bank",
        ),
        migrations.AddField(
            model_name="balancelog",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balance_logs",
                to="api.organization",
                verbose_name="Организация",
            ),
        ),
        migrations.AddField(
            model_name="balancelog",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.payment",
                verbose_name="Связанный платеж",
            ),
        ),
    ]
