# Generated by Django 4.2.17 on 2025-05-29 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_balancelog_organization_payment_delete_bank_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="opearion_id",
            new_name="operation_id",
        ),
    ]
